esphome:
  platform: esp32
  name: century-vs-pump-controller
  board: pico32
  on_boot:
    then:
      light.turn_on:
        id: id_light_1
        blue: 1.0
        brightness: 0.3
        green: 1.0
        red: 1.0
wifi:
  ap:
    password: !secret ap_PWD
    ssid: century-vs-pump-controller
  password: !secret wifi_PWD
  ssid: !secret wifi_SSID
captive_portal:
logger:
api:
  password: !secret api_PWD
ota:
  password: !secret ota_PWD
time:
  - platform: homeassistant
    id: homeassistant_time
external_components:
  # Needed to implement latest modbus user-defined function handling
  - source:
      type: git
      url: https://github.com/gazoodle/esphome
      ref: bug-fix-modbus-user-defined-function-handling
    components: [modbus]
  # Location of CenturyVSPump component implementation
  - source:
      type: git
      url: https://github.com/gazoodle/CenturyVSPump
      ref: main
binary_sensor:
  - platform: gpio
    name: Pool Pump Controller button
    pin:
      inverted: True
      number: GPIO39
button:
  - platform: template
    name: Pool Pump Controller Demand 600RPM
    id: id_button_7
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 600
  - platform: template
    name: Pool Pump Controller Demand 2600RPM
    id: id_button_6
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 2600
  - platform: template
    name: Pool Pump Controller Demand 3450RPM
    id: id_button_8
    on_press:
      then:
        - number.set:
            id: id_number_rpm
            value: 3450
centuryvspump:
light:
  - platform: neopixelbus
    name: Pool Pump Controller LED
    id: id_light_1
    num_leds: 1
    pin: GPIO27
    variant: SK6812
modbus:
  id: id_modbus_3
number:
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    id: id_number_rpm
sensor:
  - platform: wifi_signal
    name: Pool Pump Controller Wifi Signal
    update_interval: 60min
  - platform: centuryvspump
    name: Pool Pump Controller RPM
    type: rpm
    unit_of_measurement: RPM
  - platform: centuryvspump
    name: Pool Pump Controller Demand
    address: 3
    page: 0
    scale: 4
    type: custom
    unit_of_measurement: RPM
switch:
  - platform: centuryvspump
    name: Pool Pump Controller Run
    id: id_switch_4
uart:
  id: id_uart_2
  baud_rate: 9600
  debug:
  rx_pin: GPIO22
  tx_pin: GPIO19
web_server:
  local: True
  port: 80
